#
#  Copyright (c) 2020 Broadcom. All rights reserved.
#
#  This software may be modified and distributed under the terms
#  of the MIT license. See the LICENSE file for details.
#
version: '2'
services:
  lac:
    image: caliveapicreator/5.3.00
    privileged: true
    stdin_open: true
    tty: true
    environment:
      RDS_HOSTNAME: "lac_mysqldb"
      RDS_PORT: "3306"
      RDS_USERNAME: "db_admin"
      RDS_PASSWORD: "7layer"
      RDS_DB_NAME: "lacadmindb"
      CATALINA_OPTS: "--add-modules java.xml.bind $CATALINA_OPTS"
      CA_ACCEPT_LICENSE: "ENU"
      LAC_DEFAULT_LICENSE_FILE: "/home/AricDay/lac_license.json"
      LAC_ADMIN_MAX_CONN: "100"
    links:
      - lac_mysqldb
    ports:
      - "8081:8080"
    expose:
      - "8081"
  lac_mysqldb:
    image: mysql:5.7
    privileged: true
    environment:
      - MYSQL_ROOT_PASSWORD=7layer
      - MYSQL_DATABASE=lacadmindb
      - MYSQL_USER=db_admin
      - MYSQL_PASSWORD=7layer
    expose:
      - "3306"
    # volumes:
    #   # - ./lac_mysql:/var/lib/mysql
    #   - /var/lib/mysql
    #   - ./files/mysql/scripts/lacstartup/:/docker-entrypoint-initdb.d/
