#
#  Copyright (c) 2020 Broadcom. All rights reserved.
#
#  This software may be modified and distributed under the terms
#  of the MIT license. See the LICENSE file for details.
#
version: '2'
services:
  lac:
    image: caliveapicreator/5.3.00
    privileged: true
    stdin_open: true
    tty: true
    environment:
      CA_ACCEPT_LICENSE: "ENU"
      LAC_DEFAULT_LICENSE_FILE: "/license/lac_license.json"
    ports:
      - "8081:8080"
    expose:
      - "8081"
    volumes:
      - /home/AricDay/lac_license.json:/license/lac_license.json
      #- /home/AricDay/CALiveAPICreator.repository:/home/tomcat/CALiveAPICreator.repository
      #- /home/AricDay/databases:/usr/local/CALiveAPICreator/databases
  lac_mysqldb:
    image: mysql:5.7
    privileged: true
    environment:
      - MYSQL_ROOT_PASSWORD=7layer
      - MYSQL_DATABASE=lacadmindb
      - MYSQL_USER=db_admin
      - MYSQL_PASSWORD=7layer
    expose:
      - "3306"
